### ISSUE TITLE
 is too small to be an ELF executable: only found 0 bytes

### ISSUE THREAD

**Issue by s3hengwu** [whilu/TPShareLogin#10]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.un.android.app-1/lib/arm/libweibosdkcore.so" is too small to be an ELF executable: only found 0 bytes
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:371)
                                                       at java.lang.System.loadLibrary(System.java:989)
                                                       at com.sina.weibo.sdk.net.HttpManager.<clinit>(HttpManager.java:83)
                                                       at com.sina.weibo.sdk.net.NetUtils.internalHttpRequest(NetUtils.java:46)
                                                       at com.sina.weibo.sdk.utils.AidTask.loadAidFromNet(AidTask.java:344)
                                                       at com.sina.weibo.sdk.utils.AidTask.access$3(AidTask.java:331)
                                                       at com.sina.weibo.sdk.utils.AidTask$2.run(AidTask.java:203)
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by whilu** [comment]
@s3hengwu 最新的 v1.1.0 已经修复此问题😄
