### ISSUE TITLE
微博bug，机型适配 nexus 4 6.0.1

### ISSUE THREAD

**Issue by UC10D** [whilu/TPShareLogin#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileOutputStream.close()' on a null object reference
                                                                          at co.lujun.tpsharelogin.c.a.a(ImageUtils.java:53)
                                                                          at co.lujun.tpsharelogin.platform.weibo.b.run(AssistActivity.java:153)
                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by UC10D** [comment]
6.0
 读写sdk 需要权限。可以考虑加一下

**Comment by UC10D** [comment]
requestPermission()
checkPermission()
