### ISSUE TITLE
gradle方式引入类库失败

### ISSUE THREAD

**Issue by sendtion** [whilu/TPShareLogin#7]
![image](https://cloud.githubusercontent.com/assets/9346618/20047665/57d84b06-a4f1-11e6-8453-bda48ccbd39d.png)

**Comment by whilu** [comment]
Please try again, it's available now! 
If you want to get the latest library, try 'JitPack': 

``` xml
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    compile 'com.github.whilu:TPShareLogin:-SNAPSHOT'
}
```

**Comment by sendtion** [comment]
@whilu 好的，我试试看

**Comment by sendtion** [comment]
这种方式可以引入，但是还有问题，好像是so包没有找到。然后我作为一个module导入，再引入so文件没问题了。
但是调用微博还是有问题。具体表现为点击调用按钮，发生崩溃，授权界面显示成功了，抛出了异常。
异常代码：
`11-08 11:21:27.529 2052-2052/com.bri.cdstm E/ActivityThread: Activity com.bri.cdstm.ui.LoginActivity has leaked IntentReceiver co.lujun.tpsharelogin.platform.weibo.WBManager$ReceiveBroadCast@70421c4 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                             android.app.IntentReceiverLeaked: Activity com.bri.cdstm.ui.LoginActivity has leaked IntentReceiver co.lujun.tpsharelogin.platform.weibo.WBManager$ReceiveBroadCast@70421c4 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                 at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:920)
                                                                 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:721)
                                                                 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1182)
                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1156)
                                                                 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:564)
                                                                 at co.lujun.tpsharelogin.platform.weibo.WBManager.onLoginWithWB(WBManager.java:39)
                                                                 at com.bri.cdstm.ui.LoginActivity.onClick(LoginActivity.java:323)
                                                                 at android.view.View.performClick(View.java:5207)
                                                                 at android.view.View$PerformClick.run(View.java:21177)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)`

**Comment by whilu** [comment]
@s3hengwu 最新的 v1.1.0 已经修复此问题😄
